stages:
  - install_deps
  - test
  - build
  - package

default:
  image: node:18.14.2
  before_script:
    - npm i bun -g --quiet

Install Dependencies:
  stage: install_deps
  cache:
    key:
      files:
        - bun.lockb
    paths:
      - node_modules
    policy: pull-push
  script:
    - bun i

Build:
  stage: build
  cache:
    key:
      files:
        - bun.lockb
    paths:
      - node_modules
    policy: pull
  script:
    - bun run build
  artifacts:
    paths:
      - public
